# Architecture
arch: birealnet18

# ===== Dataset ===== #
data_url: ./data/imagenet
set: ImageNet
num_classes: 1000
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
re_prob: 0.25
re_mode: pixel
re_count: 1
mix_up: 0.
cutmix: 0.

# ===== Learning Rate Policy ======== #
optimizer: adam
base_lr: 0.002
warmup_lr: 0.000006
min_lr: 0.00001
lr_scheduler: lambda_lr
warmup_length: 0


# ===== Network training config ===== #
amp_level: O1
keep_bn_fp32: True
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 5.
is_dynamic_loss_scale: True
epochs: 256
label_smoothing: 0.1
loss_scale: 1024
weight_decay: 0.
momentum: 0.9
batch_size: 128

# ===== Hardware setup ===== #
num_parallel_workers: 32
device_target: Ascend

# ===== Model config ===== #
